### ISSUE TITLE
Conduct user interviews

### ISSUE THREAD

**Issue by anandxgithub** [TechnikInc/openFDA-DesignPrototype#27]

**Comment by abinelson** [comment]
![technik_18f_carddeck](https://cloud.githubusercontent.com/assets/13103569/8437554/b4642caa-1f2d-11e5-94ca-f30e8d67644e.jpg)

**Comment by abinelson** [comment]
![technik_18f_brainstorm](https://cloud.githubusercontent.com/assets/13103569/8437561/c919af58-1f2d-11e5-889e-0436e7872615.jpg)

**Comment by abinelson** [comment]
![18f usability test screen shot](https://cloud.githubusercontent.com/assets/13103569/8438011/1b607ac8-1f31-11e5-8ee0-52d52be20921.PNG)
